---
db_connection_params:
  snowflake_username: # e.g., jbloggs@email.com
  snowflake_pass:
  snowflake_account: <snowflake_account>.ap-southeast-2
  snowflake_wh:
  snowflake_db:
  snowflake_db_schema:
